# Generated by Django 3.2.10 on 2021-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimumreal', models.FloatField()),
                ('Minimumimag', models.FloatField()),
                ('Maximumreal', models.FloatField()),
                ('Maximumimag', models.FloatField()),
                ('MaxInteration', models.IntegerField()),
                ('xaxis', models.IntegerField()),
                ('yaxis', models.IntegerField()),
            ],
        ),
    ]
