# Generated by Django 3.2.10 on 2021-12-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='MaxInteration',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Maximumimag',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Maximumreal',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Minimumimag',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='xaxis',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='yaxis',
        ),
    ]
