# Generated by Django 3.2.10 on 2021-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20211212_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='MaxInteration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='Maximumimag',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='Maximumreal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='Minimumimag',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='xaxis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='yaxis',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Minimumreal',
            field=models.FloatField(null=True),
        ),
    ]
